@startuml
start
:接收【台語音標】字串;
if (查驗傳入之【台語音標】是否符合標準格式?) then (否)
  #pink:直接回傳原字串;
  stop
else (是)
  :自【台語音標】萃取【無調號標音】、【調號】\n（【無調號標音】=【聲母】+【韻母】）;
  :依【聲母轉換表】之【聲母索引】比對【無調號標音】，萃取【轉換後聲母】）;
  if (是否找到【聲母索引】？) then (否)
    #pink:【聲母】設定為空字串（零聲母）;
    #pink:【韻母】同【無調號標音】;
  else (是)
    :將【聲母】替換成【轉換後聲母】;
    :自【無調號標音】萃取【韻母】;
  endif
  :依【韻母對映表】之【韻母索引】比對【韻母】，萃取【轉換後韻母】;
  if (是否找到【韻母索引】？) then (否)
    #pink:【韻母】維持不變;
  else (是)
    :將【韻母】替換成【轉換後韻母】;
  endif
  /'if (韻母是否在映射表中?) then (否)'/
  /'  if (<color:red>韻母是否以 "o" 結尾?) then (是)'/
  /'    :替換 "o" 為 "or";'/
  /'  else (否)'/
  /'    #pink:保持韻母不變;'/
  /'  endif'/
  /'else (是)'/
  /'  :替換為對應韻母;'/
  /'endif'/
  :處理【齒音聲母連i】，需變更【聲母】之特殊狀況\n（如 "ci"、"si"、"zi"、"ji" 等）;
  :合併【聲母】、【韻母】與【調號】為【台語二式音標】;
  :回傳轉換後的【台語二式音標】;
  stop
@enduml
