@startuml
start
:讀取輸入檔案;
:逐行處理檔案內容;
repeat
  :讀取一行待處理之資料;
  if (是否為空行或註解?) then (是)
    :跳過該行;
  else (否)
    #pink:將整行資料依【間隔字元】分切為多個【資料欄】;
    if (【資料欄】總數至少需有2個?\n（至少需有【漢字欄】、【台語音標欄】）) then (是)
      :取得【台語音標】進行轉換作業\n convert_TLPA_to_MPS2();
      :將【台語音標欄】之拼音變更成轉換後之【台語注音二式音標】;
    else (否)
      #pink:跳過該行;
    endif
  endif
repeat while (還有未處理的行?)
:寫入輸出檔案;
stop
@enduml
