@startyaml
#highlight "切語上字"
#highlight "切語上字" / "漢字"
#highlight "切語下字"
#highlight "切語下字" / "漢字"

' 欲查詢《廣韻》切語之漢字，如：東
漢字: "東" 
切語: "德紅"
切語上字: 
    漢字: 德
    發聲部位: 舌頭音
    聲母: 德
    擬音: t
    清濁: 清
切語下字: 
    漢字: 紅
	jip: 通
    韻目: 東
	等: 一
	呼: 開
	韻母: 東一
    調: 平
    擬音: ong
@endyaml