-- DDL generated by Postico 1.5.21
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE han_ji (
    id SERIAL PRIMARY KEY,
    han_ji character varying(6),
    chu_im character varying(15),
    freq real,
    siann character varying(3),
    un character varying(5),
    tiau integer,
    old_chu_im character varying(15),
    sni_siann character varying(3),
    sni_un character varying(5)
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX han_ji_pkey ON han_ji(id int4_ops);
